version: '3.8'

services:
  app:
    image: golang:1.23.4-alpine
    working_dir: /app
    command: sh -c "
      apk add --no-cache ca-certificates git curl netcat-openbsd &&
      go mod download &&
      # Wait for Postgres to be ready
      echo 'Waiting for PostgreSQL to start...' &&
      for i in {1..30}; do
        if nc -z postgres 5432; then
          echo 'PostgreSQL is up and running!' &&
          break
        fi
        echo 'Waiting for PostgreSQL...' &&
        sleep 1
      done &&
      # Build with VCS flag disabled (fixes CI build issue)
      go build -buildvcs=false -o urlshortener ./cmd/server &&
      echo 'Starting URL Shortener API...' &&
      ./urlshortener
      "
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - BASE_URL=http://localhost:8081
      - ENVIRONMENT=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_test_password
      - POSTGRES_DB=url_shortener_test
      - MASTER_PASSWORD=dev_master_password
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRATION=24h
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - url-shortener

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_test_password
      - POSTGRES_DB=url_shortener_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge

volumes:
  postgres_data: 