basePath: /api
definitions:
  domain.CreateShortLinkRequest:
    properties:
      custom_alias:
        type: string
      expiration_date:
        type: string
      url:
        type: string
    type: object
  domain.LinkClick:
    properties:
      browser:
        type: string
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      device:
        type: string
      id:
        type: string
      ip_address:
        type: string
      os:
        type: string
      referrer:
        type: string
      short_link_id:
        type: string
      user_agent:
        type: string
    type: object
  domain.LinkStats:
    properties:
      clicks_by_day:
        additionalProperties:
          type: integer
        type: object
      last_clicked:
        type: string
      recent_clicks:
        items:
          $ref: '#/definitions/domain.LinkClick'
        type: array
      top_browsers:
        additionalProperties:
          type: integer
        type: object
      top_devices:
        additionalProperties:
          type: integer
        type: object
      top_os:
        additionalProperties:
          type: integer
        type: object
      top_referrers:
        additionalProperties:
          type: integer
        type: object
      total_clicks:
        type: integer
    type: object
  domain.ShortLink:
    properties:
      code:
        type: string
      created_at:
        type: string
      custom_alias:
        type: string
      expiration_date:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      updated_at:
        type: string
      url:
        allOf:
        - $ref: '#/definitions/domain.URL'
        description: Embedded URL information when fetching a short link
      url_id:
        type: string
    type: object
  domain.URL:
    properties:
      created_at:
        type: string
      hash:
        type: string
      id:
        type: string
      original_url:
        type: string
      updated_at:
        type: string
    type: object
  domain.UpdateShortLinkRequest:
    properties:
      custom_alias:
        type: string
      expiration_date:
        type: string
      is_active:
        type: boolean
    type: object
  handlers.TokenRequest:
    properties:
      master_password:
        example: your_master_password
        type: string
    required:
    - master_password
    type: object
  handlers.TokenResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
host: r.menezmethod.com
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: A RESTful API for shortening URLs with analytics.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: URL Shortener API
  version: "1.0"
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      description: Generate a JWT token using the master password
      parameters:
      - description: Token request with master password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token generated successfully
          schema:
            $ref: '#/definitions/handlers.TokenResponse'
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized - Invalid master password
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate authentication token
      tags:
      - auth
  /links:
    post:
      consumes:
      - application/json
      description: Create a new short link for a URL, optionally with a custom alias
      parameters:
      - description: Link creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateShortLinkRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Link created successfully
          schema:
            $ref: '#/definitions/domain.ShortLink'
        "400":
          description: Invalid request or URL
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new short link
      tags:
      - links
  /links/{code}:
    delete:
      consumes:
      - application/json
      description: Delete a short link by its code
      parameters:
      - description: Short link code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No content
        "400":
          description: Invalid code
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Link not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a short link
      tags:
      - links
    get:
      consumes:
      - application/json
      description: Get details of a short link using its code
      parameters:
      - description: Short link code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Link details
          schema:
            $ref: '#/definitions/domain.ShortLink'
        "400":
          description: Invalid code
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Link not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get a short link by code
      tags:
      - links
    put:
      consumes:
      - application/json
      description: Update properties of an existing short link
      parameters:
      - description: Short link code
        in: path
        name: code
        required: true
        type: string
      - description: Update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateShortLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated link
          schema:
            $ref: '#/definitions/domain.ShortLink'
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Link not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a short link
      tags:
      - links
  /links/{code}/stats:
    get:
      consumes:
      - application/json
      description: Get usage statistics for a short link
      parameters:
      - description: Short link code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Link statistics
          schema:
            $ref: '#/definitions/domain.LinkStats'
        "400":
          description: Invalid code
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Link not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get link statistics
      tags:
      - links
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Enter 'Bearer ' followed by your JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
