name: Postman API Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  postman-tests:
    name: Run Postman Collection Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    # Set up Docker Compose
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.5.1

    - name: Start services with CI-specific Docker Compose
      run: |
        # Use the CI-specific docker-compose file
        echo "Starting Docker Compose services..."
        docker compose -f docker-compose.ci.yml up -d
        
        # Wait for services to be ready
        echo "Waiting for services to start..."
        sleep 30
        
        # Debug output
        echo "Docker Compose services status:"
        docker compose -f docker-compose.ci.yml ps
        echo "Container logs:"
        docker compose -f docker-compose.ci.yml logs --tail=50

    - name: Create Newman environment file
      run: |
        cat > newman-environment.json << EOL
        {
          "name": "URL_Shortener_API_CI_Environment",
          "values": [
            {
              "key": "baseUrl",
              "value": "http://localhost:8081",
              "enabled": true
            },
            {
              "key": "apiPath",
              "value": "api",
              "enabled": true
            },
            {
              "key": "masterPassword",
              "value": "dev_master_password",
              "enabled": true
            }
          ]
        }
        EOL

    - name: Run Postman collection tests
      run: |
        newman run ./postman/collections/master_collection.json \
          -e newman-environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export postman-results.html \
          --bail

    - name: Upload Postman test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: postman-test-results
        path: postman-results.html
        
    - name: Stop Docker Compose services
      if: always()
      run: docker compose -f docker-compose.ci.yml down 