name: Go Unit Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
          POSTGRES_DB: url_shortener_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

    - name: Run tests
      env:
        TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
        TEST_MASTER_PASSWORD: ${{ secrets.TEST_MASTER_PASSWORD }}
        TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        ginkgo -r -v --cover --coverprofile=coverage.out ./...

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out

    - name: Generate coverage HTML
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage HTML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: coverage.html 